name: flutter_demo #应用名称
description: A new Flutter application. #应用描述
#Dart运行环境区间
environment:
  sdk: ">=2.12.0-0 <3.0.0"
#Flutter依赖库
dependencies:
  flutter:
    sdk: flutter

     # 基础的点击
  tapped: ^2.0.0-nullsafety.0
  # map取值
  safemap: ^2.0.0-nullsafety.0
  # 加载动画库
  flutter_spinkit: ^5.0.0
  # 播放器
  video_player: ^2.1.6
  dio: ^4.0.4
  cupertino_icons: ^1.0.4
  date_format: '2.0.4'
  event_bus: '2.0.0'
  provider: ^4.3.2
  http: '>=0.11.3+12'
  path_provider: ^2.0.7
  carousel_slider:
  cached_network_image:
  shared_preferences: ^2.0.11
  flutter_webview_plugin:
  share:
  fluttertoast: ^8.0.7
  battery:
  intl:
  device_info:

dev_dependencies:
  flutter_driver:
    sdk: flutter

  build_runner: ^1.4.0
  build_web_compilers: ^2.0.0

# PUBSPEC CHECKSUM: 7613
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
   - assets/
   - assets/mock/
   - assets/images/
   - assets/images/2.0x/
   - assets/images/2.0x/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
